# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20150416_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortorder', models.PositiveIntegerField(db_index=True, help_text='Indica la posición de la publicidad dentro del newsletter', verbose_name='Orden')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(default='a', verbose_name='text')),
                ('url', models.URLField(verbose_name='link')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='newsletter/images/%Y/%m/%d', verbose_name='image')),
            ],
            options={
                'verbose_name': 'publicidad',
                'ordering': ('sortorder',),
                'verbose_name_plural': 'publicidades',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('sortorder',), 'verbose_name': 'artículo', 'verbose_name_plural': 'artículos'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'envio', 'verbose_name_plural': 'envios'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'suscripción', 'verbose_name_plural': 'suscripciones'},
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='newsletter/images/%Y/%m/%d', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sortorder',
            field=models.PositiveIntegerField(db_index=True, help_text='Indica la posición del artículo dentro del post', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(help_text='E-mail de envio', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='send_html',
            field=models.BooleanField(default=True, help_text='Enviar el mensaje como HTML?', verbose_name='Enviar html?'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='sender',
            field=models.CharField(help_text='Nombre del remitente', max_length=200, verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del newsletter'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Message', verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='prepared',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='preparado'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de envio'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sending',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='en proceso'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sent',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='enviado'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='If you select none, the system will automatically find the subscribers for you.', to='newsletter.Subscription', verbose_name='suscriptores'),
        ),
        migrations.AddField(
            model_name='publicity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicities', to='newsletter.Message', verbose_name='message'),
        ),
    ]
