# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20160328_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='ip',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribe_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de suscripción'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='suscrito'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='no suscrito'),
        ),
    ]
